### ISSUE TITLE
WSS Client sample code

### ISSUE THREAD

**Issue by raul-gherman** [zephyrchien/kaminari#10]
hello @zephyrchien , could you please provide some working sample code for a client connecting to wss?
I am very interested in `kaminari` but having a hard time getting started...

Best,

Raul

**Comment by zephyrchien** [comment]
Hi @raul-gherman , thank you for your interests in this project ~! ( it's not actively maintained tho..)

The code still compiles with the latest nightly toolchain but some old experimental code are not updated( two years ago there was no async trait so I had to use GAT + impl trait type deduction in associate type). Meanwhile the 3rd-party dependencies especially rustls are out of date..

If you are still interested in playing with this library, you could look into the client cmd tool here https://github.com/zephyrchien/kaminari/blob/master/cmd/src/client.rs
and the generated doc to help nevigate types and functions https://docs.rs/kaminari/0.12.0/kaminari/ (not that well documented tho..)

There're two traits `AsyncConnect` and `AsyncAccept` representing types that can perform an async connect or accept.
Implementations for each protocol are in `nop.rs`, `ws.rs`, `tls.rs`...

You could build a `TlsConnect` from `TlsConf` over `NopConnect`, then build a `WsConnect` from `WsConf` over `TlsConnect`. After that, call `connect` method of the prepared connector, with a stream(usually `tokio::TcpStream`).
When `connect(stream).await` is called, a bottom-up handshake is performed(tcp => tls => ws = wss).

If you have any further questions feel free to ask me. Happy hacking!

**Comment by zephyrchien** [comment]
The websocket part is based this library https://github.com/zephyrchien/lightws. It's not actively maintained as well tho, since RFC6455 is just there and wont change, there's no update required unless there's a bug. You could run tests to check if the library works well.

Be careful that `lightws` is not as general-purpose as `tungstenite`. It's for effectively handling streamed data(not data frames) without copying back and forth.

**Comment by raul-gherman** [comment]
very small change needed to be done in order to compile with latest nightly and all dev libraries brought up-to-date... but I am afraid I am not there yet -- there = to pick it up from here (hence my previous request for sample wss client code...)
I will go ahead and try to figure it out -- given some proper documentation, you could have a very nice impact with this crate

**Comment by raul-gherman** [comment]
if and when you have time to consider https://github.com/zephyrchien/kaminari/pull/11

**Comment by zephyrchien** [comment]
Let me collect my memories.., here's a sample of pseudo code:

```rust
let ws_conf = opt::get_ws_conf('ws;host=example.com;path=/ws');
let client = ws::WsConnect::new(nop::NopConnect {}, ws_conf);

let stream = tokio::TcpStream::connect(...);
let mut buf = vec![0u8; 0x1000]; // buffer to receive headers during a handshake. Can be reused later.
let stream = client.connect(stream, &mut buf);
```

**Comment by raul-gherman** [comment]
@zephyrchien here is my current version of almost working code -- almost because I still need to figure out a way to determine `Opcode` and act based on that (I have 2 projects, one that needs to communicate using `protobuf` over `wss`, and here `Binary` msg is needed, and another one with `json` over `wss`, and here `Text` is needed... also `Ping` to keep connections alive, sending it every 30s or so...):

```rust
use std::error::Error;

use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpStream;

use kaminari::nop::NopConnect;
use kaminari::tls::TlsConnect;
use kaminari::AsyncConnect;
use kaminari::{opt, ws};

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let ws_conf = opt::get_ws_conf("ws;host=demo.redacted.com;path=/").unwrap();
    let tls = opt::get_tls_client_conf("tls;sni=demo.redacted.com;alpn=h2,http/1.1").unwrap();
    let client = ws::WsConnect::new(TlsConnect::new(NopConnect {}, tls), ws_conf);

    let stream = TcpStream::connect("demo.redacted.com")
        .await
        .unwrap();
    let mut buf = vec![0u8; 0x1000];
    match client.connect(stream, &mut buf).await {
        Ok(mut ws_stream) => {
            println!("connected");
            // still to do:
            // figure out OpCode and act based on
            // loop {
            //     let n = ws_stream.read(&mut buf).await?;
            //     if n == 0 {
            //         break; // Connection closed
            //     }
            //     println!("Read {} bytes: {:?}", n, &buf[..n]);
            // }
        }
        Err(e) => eprintln!("{e}"),
    };

    Ok(())
}

```

**Comment by zephyrchien** [comment]
@raul-gherman the underlying library `lightws` doesn't cover such use case (by design). `lightws::Stream` is similar to `TcpStream` where only `Binary` data are supported.

https://github.com/zephyrchien/lightws/blob/master/src/stream/detail/read.rs#L155

**Comment by raul-gherman** [comment]
thank you @zephyrchien , than it is even easier :)
will you update `README`, or do you want me to raise PR with updated working sample?

**Comment by zephyrchien** [comment]
@raul-gherman  I'm tooo lazy to do that in a short term lol. Personally I think it would be helpful to add examples to [rustdoc](https://docs.rs/kaminari/0.12.0/kaminari/). (If there're other guys interested in this library ;)

**Comment by raul-gherman** [comment]
I will update readme and raise new PR, after that you can publish small increment version to `crates.io` (as I cannot do this, unless fork); we'll pick it up from there afterwards
