### ISSUE TITLE
wss mode via cdn error?

### ISSUE THREAD

**Issue by 669800** [zephyrchien/kaminari#2]

**Comment by 669800** [comment]
> 

Can't pass cdn in wss mode.
Tcp+tls is ok. Why?

**Comment by malikshi** [comment]
do you @669800 still having same problem?

**Comment by zephyrchien** [comment]
2a01f2e add `alpn=http/1.1` on client side.

**Comment by malikshi** [comment]
Kaminaris as plugin shadowsocks can't bypass CDN, using v2ray-plugin on client. I will try standalone version later

**Comment by 669800** [comment]
> Kaminaris as plugin shadowsocks can't bypass CDN, using v2ray-plugin on client. I will try standalone version later

Thank you

**Comment by 669800** [comment]
> 2a01f2e add `alpn=http/1.1` on client side.

How to add?  give an example?  I will test it. Thanks 🙏

**Comment by malikshi** [comment]
> > [2a01f2e](https://github.com/zephyrchien/kaminari/commit/2a01f2e8a62d85b4cdc8771eedda8799676c0a90) add `alpn=http/1.1` on client side.
> 
> How to add? give an example? I will test it. Thanks 🙏

https://github.com/zephyrchien/kaminari#tls-options

**Comment by 669800** [comment]
> > > [2a01f2e](https://github.com/zephyrchien/kaminari/commit/2a01f2e8a62d85b4cdc8771eedda8799676c0a90) add `alpn=http/1.1` on client side.
> 
> > 
> 
> > How to add? give an example? I will test it. Thanks 🙏
> 
> 
> 
> https://github.com/zephyrchien/kaminari#tls-options

I use browser to access, not kaminaric.

Eg
```

kaminaris 127.0.0.1:20000 127.0.0.1:30000 'ws;host=example.com;path=/ws;tls;cert=example.com.crt;key=example.com.key'

```
127.0.0.1:30000 is my nginx web path is /ws

**Comment by zephyrchien** [comment]
I've tried using `wss` to cross Cloudflare just now, with either fqdn or a custom ipv4/ipv6 ip address, no matter whether `alpn` is configured or not. This means, **there is no problem at all**.

Actually I've tested `ws` with enough cases last month, when the initial version was just released. I dont think there would be a problem with `wss`.

Below are iperf results: `iperf -> kaminaric[select any cf ip] -> cloudflare -> kaminaris -> iperf`

![iperf](https://user-images.githubusercontent.com/51367850/169675087-1752a9b9-0a11-4176-8830-e7e7d4fb2f30.jpeg)

**Comment by malikshi** [comment]
did you tests it as standalone/plugin sir?

**Comment by zephyrchien** [comment]
> 

There is definitely no difference.

**Comment by malikshi** [comment]
this my server config
```json
{
"server":"::",
"server_port":443,
"password":"Password",
"timeout":300,
"method":"chacha20-ietf-poly1305",
"fast_open":false,
"nameserver":"1.0.0.1",
"mode":"tcp_and_udp",
"plugin":"/usr/local/bin/kaminaris",
"plugin_opts":"tls;ws;path=/v2ray-plugin;host=kamipoi.domain;cert=/etc/letsencrypt/live/kamipoi.domain/fullchain.pem;key=/etc/letsencrypt/live/kamipoi.domain/privkey.pem"
}
```
i used shadowsocks app on android + v2ray-plugin and did'nt work for IP CDN/HOST CDN from cloudflare

**Comment by zephyrchien** [comment]
@malikshi You should have sni and host properly configured.
