### ISSUE TITLE
Can this connect to other WS Tunnel?

### ISSUE THREAD

**Issue by MikoyChinese** [zephyrchien/kaminari#4]
Such as gost and echo?

**Comment by zephyrchien** [comment]
For gost/v2ray(no mux), yes. 

As for ehco, the answer is no. I can confirm that it has been incorrectly using the websocket library that it depends on, where data are not encapsulated in a ws frame.

Kaminari depends on lightws, which implements most details of rfc6455, so theorily it is able to communicate with any other middlewares which also speak the standard websocket protocol.
